disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Emmanuel Ogie"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

 [params.author]
  name = "Emmanuel Ogie"
  image = "images/profile_picture.jpg"
  headline = "Game Programmer"
  links = [
    { email = "mailto:contact@emmanuelogie.com" },
    { github = "https://github.com/Oakamoore" },
    { itch-io = "https://oakamoore.itch.io/" },
    { linkedin = "https://www.linkedin.com/in/emmanuel-ogie/" },
  ]